// entrypoints/sidepanel/App.tsx
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/components/ui/input-group";
import { Label } from "@/components/ui/label";
import {
  Building2,
  ExternalLink,
  Link,
  RefreshCw,
  Sparkles,
  User,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getLinkedInPageType } from "../../lib/linkedin-scraper";
import type {
  CaptureState,
  ExtensionResponse,
  LinkedInData,
  LinkedInProfileData,
} from "../../types";

type RecentCapture = {
  linkedinUrl: string;
  name: string;
  type: "person" | "company";
  capturedAt: number;
  twentyId: string;
};

export default function App() {
  const [twentyUrl, setTwentyUrl] = useState("");
  const [hasToken, setHasToken] = useState(false);
  const [isConnected, setIsConnected] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isTesting, setIsTesting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [recentCaptures, setRecentCaptures] = useState<RecentCapture[]>([]);
  const [captureState, setCaptureState] = useState<CaptureState>({
    status: "idle",
  });
  const [autoFetchAttempts, setAutoFetchAttempts] = useState(0);

  console.log("captureState", captureState);
  const [currentTabUrl, setCurrentTabUrl] = useState<string | null>(null);
  const [isCheckingPage, setIsCheckingPage] = useState(false);

  // Computed
  const isConfigured = useMemo(() => !!twentyUrl, [twentyUrl]);

  const connectionStatus = useMemo(() => {
    if (!isConfigured) return "not-configured";
    if (!hasToken) return "no-session";
    if (isConnected) return "connected";
    return "disconnected";
  }, [isConfigured, hasToken, isConnected]);

  const statusText = useMemo(() => {
    switch (connectionStatus) {
      case "not-configured":
        return "Not configured";
      case "no-session":
        return "Not logged in";
      case "connected":
        return "Connected";
      case "disconnected":
        return "Connection failed";
      default:
        return "Unknown";
    }
  }, [connectionStatus]);

  const statusColorClass = useMemo(() => {
    switch (connectionStatus) {
      case "connected":
        return "text-emerald-400";
      case "no-session":
        return "text-amber-400";
      default:
        return "text-red-400";
    }
  }, [connectionStatus]);

  function normalizeTwentyUrl(urlValue: string): string {
    let url = urlValue.trim();
    if (!url.startsWith("http://") && !url.startsWith("https://")) {
      url = `https://${url}`;
    }

    try {
      const parsed = new URL(url);
      const hostname = parsed.hostname.toLowerCase();
      if (hostname === "twenty.com" || hostname === "www.twenty.com") {
        return `${parsed.protocol}//app.twenty.com`;
      }
      const normalizedPath =
        parsed.pathname && parsed.pathname !== "/"
          ? parsed.pathname.replace(/\/$/, "")
          : "";
      return `${parsed.origin}${normalizedPath}`;
    } catch {
      return url.replace(/\/$/, "");
    }
  }

  function getTwentyOriginPatterns(urlValue: string): string[] {
    try {
      const parsed = new URL(urlValue);
      const protocol = parsed.protocol;
      const hostname = parsed.hostname.toLowerCase();
      const hostnames = new Set<string>([hostname]);
      if (hostname.startsWith("www.")) {
        hostnames.add(hostname.replace(/^www\./, ""));
      } else {
        hostnames.add(`www.${hostname}`);
      }

      if (
        hostname === "twenty.com"
        || hostname === "www.twenty.com"
        || hostname === "app.twenty.com"
        || hostname === "api.twenty.com"
      ) {
        hostnames.add("twenty.com");
        hostnames.add("www.twenty.com");
        hostnames.add("app.twenty.com");
        hostnames.add("api.twenty.com");
      }
      return Array.from(hostnames).map((hostname) => `${protocol}//${hostname}/*`);
    } catch {
      return [];
    }
  }

  async function ensureTwentyPermission(urlValue: string): Promise<boolean> {
    const origins = getTwentyOriginPatterns(urlValue);
    if (origins.length === 0) {
      return false;
    }

    try {
      const hasPermission = await browser.permissions.contains({ origins });
      if (hasPermission) {
        return true;
      }
      return await browser.permissions.request({ origins });
    } catch (err) {
      console.error("Error requesting permission:", err);
      return false;
    }
  }

  // Load settings on mount
  useEffect(() => {
    loadSettings();
    loadRecentCaptures();
    setTimeout(() => {
      checkCurrentTab();
    }, 100);

    const handleTabUpdate = (tabId: number, changeInfo: any, tab: any) => {
      if (changeInfo.url || changeInfo.status === "complete") {
        checkCurrentTab();
      }
    };

    const handleTabActivated = (activeInfo: any) => {
      checkCurrentTab();
    };

    browser.tabs.onUpdated.addListener(handleTabUpdate);
    browser.tabs.onActivated.addListener(handleTabActivated);

    return () => {
      browser.tabs.onUpdated.removeListener(handleTabUpdate);
      browser.tabs.onActivated.removeListener(handleTabActivated);
    };
  }, []);

  // Re-check the active LinkedIn tab once configuration/auth become available.
  useEffect(() => {
    if (twentyUrl && hasToken) {
      checkCurrentTab();
    }
  }, [twentyUrl, hasToken]);

  // Reset auto-fetch attempts whenever the active URL changes.
  useEffect(() => {
    setAutoFetchAttempts(0);
  }, [currentTabUrl]);

  // If state is still idle on a LinkedIn page, retry automatically without requiring a button click.
  useEffect(() => {
    if (!twentyUrl || !hasToken || isCheckingPage || isLoading) return;
    if (!currentTabUrl || !getLinkedInPageType(currentTabUrl)) return;
    if (captureState.status !== "idle") return;
    if (autoFetchAttempts >= 3) return;

    const timeout = setTimeout(() => {
      setAutoFetchAttempts((prev) => prev + 1);
      checkCurrentTab();
    }, 400);

    return () => clearTimeout(timeout);
  }, [
    twentyUrl,
    hasToken,
    isCheckingPage,
    isLoading,
    currentTabUrl,
    captureState.status,
    autoFetchAttempts,
  ]);

  async function checkCurrentTab() {
    try {
      let tabs = await browser.tabs.query({
        active: true,
        currentWindow: true,
      });

      if (!tabs || tabs.length === 0 || !tabs[0]?.url) {
        tabs = await browser.tabs.query({
          active: true,
        });
      }

      // If still no tabs, try getting the last focused window
      if (!tabs || tabs.length === 0 || !tabs[0]?.url) {
        const windows = await browser.windows.getAll({ populate: true });
        for (const window of windows) {
          if (window.tabs) {
            const activeTab = window.tabs.find((tab) => tab.active);
            if (activeTab?.url) {
              tabs = [activeTab];
              break;
            }
          }
        }
      }

      if (tabs && tabs.length > 0 && tabs[0]?.url) {
        const url = tabs[0].url;
        console.log("Current tab URL:", url);
        setCurrentTabUrl(url);
        const pageType = getLinkedInPageType(url);
        console.log("Page type:", pageType);
        if (pageType && tabs[0].id) {
          await checkPageForCapture(tabs[0].id, url, pageType);
        } else {
          setCaptureState({ status: "idle" });
        }
      } else {
        console.log("No active tab found");
        setCurrentTabUrl(null);
        setCaptureState({ status: "idle" });
      }
    } catch (err) {
      console.error("Error checking current tab:", err);
      setCurrentTabUrl(null);
      setCaptureState({ status: "idle" });
    }
  }

  async function checkPageForCapture(
    tabId: number,
    url: string,
    pageType: "person" | "company"
  ) {
    if (!twentyUrl || !hasToken) {
      setCaptureState({ status: "idle" });
      return;
    }

    setIsCheckingPage(true);
    setCaptureState({ status: "loading" });

    try {
      // Try to get data from content script first
      let scrapedData: LinkedInData | undefined;
      try {
        const scrapeResponse = (await browser.tabs.sendMessage(tabId, {
          type: "GET_PAGE_DATA",
        })) as ExtensionResponse<LinkedInData>;
        if (scrapeResponse.success && scrapeResponse.data) {
          scrapedData = scrapeResponse.data;
        }
      } catch (e) {
        // Content script might not be loaded, that's okay
        console.log(
          "Could not get data from content script, will check duplicate anyway"
        );
      }

      // Check for duplicate
      const response = (await browser.runtime.sendMessage({
        type: "CHECK_DUPLICATE",
        payload: {
          linkedinUrl: url.split("?")[0],
          pageType,
          scrapedData,
        },
      })) as ExtensionResponse<{
        exists: boolean;
        record?: { id: string; type: string };
        matchedBy?: string;
      }>;

      if (response.success) {
        if (response.data?.exists && response.data.record) {
          setCaptureState({
            status: "exists",
            existingRecord: {
              id: response.data.record.id,
              type: response.data.record.type as "person" | "company",
            },
            data: scrapedData,
          });
        } else {
          setCaptureState({
            status: "ready",
            data: scrapedData,
          });
        }
      } else {
        if (
          response.error?.includes("not configured") ||
          response.error?.includes("No authentication")
        ) {
          setCaptureState({ status: "idle", error: "Configure Twenty URL" });
        } else {
          setCaptureState({ status: "error", error: response.error });
        }
      }
    } catch (err) {
      console.error("Error checking page:", err);
      setCaptureState({ status: "error", error: "Failed to check page" });
    } finally {
      setIsCheckingPage(false);
    }
  }

  async function handleCapture() {
    if (captureState.status !== "ready" || !captureState.data) return;

    setCaptureState({ ...captureState, status: "saving" });

    try {
      const response = (await browser.runtime.sendMessage({
        type: "CREATE_RECORD",
        payload: captureState.data,
      })) as ExtensionResponse<{ id: string }>;

      if (response.success && response.data) {
        setCaptureState({
          status: "saved",
          existingRecord: {
            id: response.data.id,
            type: captureState.data.type,
          },
          data: captureState.data,
        });
        setSuccess("Added to Twenty CRM!");
        setTimeout(() => setSuccess(null), 3000);
        await loadRecentCaptures();

        // Update to exists state after a delay
        setTimeout(() => {
          setCaptureState((prev) => ({ ...prev, status: "exists" }));
        }, 2000);
      } else {
        setCaptureState({
          ...captureState,
          status: "error",
          error: response.error,
        });
        setError(response.error || "Failed to save");
      }
    } catch (err) {
      console.error("Error capturing:", err);
      setCaptureState({
        ...captureState,
        status: "error",
        error: "Failed to save",
      });
      setError("Failed to save");
    }
  }

  async function handleOpenInTwenty() {
    if (!captureState.existingRecord || !twentyUrl) return;
    const { id, type } = captureState.existingRecord;
    browser.tabs.create({
      url: `${twentyUrl}/object/${type}/${id}`,
    });
  }

  async function handleUpdate() {
    if (!captureState.existingRecord || !currentTabUrl) return;

    const tabs = await browser.tabs.query({
      active: true,
      currentWindow: true,
    });
    if (!tabs[0]?.id) return;

    setCaptureState({ ...captureState, status: "saving" });

    try {
      // Get fresh data from content script
      let scrapedData: LinkedInData | undefined;
      try {
        const scrapeResponse = (await browser.tabs.sendMessage(tabs[0].id, {
          type: "GET_PAGE_DATA",
        })) as ExtensionResponse<LinkedInData>;
        if (scrapeResponse.success && scrapeResponse.data) {
          scrapedData = scrapeResponse.data;
        }
      } catch (e) {
        setError("Could not get page data. Please refresh the LinkedIn page.");
        setCaptureState({ ...captureState, status: "error" });
        return;
      }

      if (!scrapedData) {
        setError("Could not extract profile data");
        setCaptureState({ ...captureState, status: "error" });
        return;
      }

      const response = (await browser.runtime.sendMessage({
        type: "UPDATE_RECORD",
        payload: {
          id: captureState.existingRecord.id,
          type: captureState.existingRecord.type,
          data: scrapedData,
        },
      })) as ExtensionResponse<{ id: string }>;

      if (response.success) {
        setCaptureState({
          ...captureState,
          status: "saved",
          data: scrapedData,
        });
        setSuccess("Updated in Twenty CRM!");
        setTimeout(() => setSuccess(null), 3000);
        setTimeout(() => {
          setCaptureState((prev) => ({ ...prev, status: "exists" }));
        }, 2000);
      } else {
        setCaptureState({
          ...captureState,
          status: "error",
          error: response.error,
        });
        setError(response.error || "Failed to update");
      }
    } catch (err) {
      console.error("Error updating:", err);
      setCaptureState({
        ...captureState,
        status: "error",
        error: "Failed to update",
      });
      setError("Failed to update");
    }
  }

  function getCaptureButtonText(): string {
    switch (captureState.status) {
      case "idle":
        return "Checking profile...";
      case "loading":
        return "Checking...";
      case "ready":
        return "Add to Twenty CRM";
      case "exists":
        return "Open in Twenty";
      case "saving":
        return "Saving...";
      case "saved":
        return "Saved!";
      case "error":
        return captureState.error || "Error";
      default:
        return "Twenty CRM";
    }
  }

  async function loadSettings() {
    setIsLoading(true);
    try {
      const response = (await browser.runtime.sendMessage({
        type: "GET_SETTINGS",
      })) as ExtensionResponse<{ twentyUrl: string; hasToken: boolean }>;

      if (response.success && response.data) {
        setTwentyUrl(normalizeTwentyUrl(response.data.twentyUrl || ""));
        setHasToken(response.data.hasToken || false);

        if (response.data.hasToken) {
          await testConnection();
        }
      }
    } catch (err) {
      console.error("Error loading settings:", err);
      setError("Failed to load settings");
    } finally {
      setIsLoading(false);
    }
  }

  async function loadRecentCaptures() {
    try {
      const response = (await browser.runtime.sendMessage({
        type: "GET_RECENT_CAPTURES",
      })) as ExtensionResponse<RecentCapture[]>;

      if (response.success && response.data) {
        setRecentCaptures(response.data);
      }
    } catch (err) {
      console.error("Error loading recent captures:", err);
    }
  }

  async function saveSettings() {
    if (!twentyUrl) {
      setError("Please enter your Twenty URL");
      return;
    }

    const url = normalizeTwentyUrl(twentyUrl);
    setTwentyUrl(url);

    setIsSaving(true);
    setError(null);
    setSuccess(null);

    try {
      const hasPermission = await ensureTwentyPermission(url);
      if (!hasPermission) {
        setError("Permission denied. Please allow access to your Twenty domain.");
        return;
      }

      const response = (await browser.runtime.sendMessage({
        type: "SAVE_SETTINGS",
        payload: { twentyUrl: url },
      })) as ExtensionResponse;

      if (response.success) {
        setSuccess("Settings saved!");
        // Reload to check token
        await loadSettings();
      } else {
        setError(response.error || "Failed to save settings");
      }
    } catch (err) {
      console.error("Error saving settings:", err);
      setError("Failed to save settings");
    } finally {
      setIsSaving(false);
      setTimeout(() => {
        setSuccess(null);
      }, 3000);
    }
  }

  async function testConnection() {
    if (!twentyUrl) {
      setError("Please enter your Twenty URL");
      return;
    }

    setIsTesting(true);
    setError(null);

    try {
      const normalizedUrl = normalizeTwentyUrl(twentyUrl);
      const hasPermission = await ensureTwentyPermission(normalizedUrl);
      if (!hasPermission) {
        setError("Permission denied. Please allow access to your Twenty domain.");
        setIsConnected(false);
        return;
      }

      const response = (await browser.runtime.sendMessage({
        type: "TEST_CONNECTION",
      })) as ExtensionResponse<{ connected: boolean }>;

      const connected = response.success && response.data?.connected === true;
      setIsConnected(connected);

      if (!connected) {
        setError(
          response.error || "Connection test failed. Check your URL and login."
        );
      } else {
        setSuccess("Connection successful!");
        setTimeout(() => setSuccess(null), 3000);
      }
    } catch (err) {
      console.error("Error testing connection:", err);
      setIsConnected(false);
      const errorMessage =
        err instanceof Error ? err.message : "Connection test failed";
      setError(errorMessage);
    } finally {
      setIsTesting(false);
    }
  }

  function openTwenty() {
    if (twentyUrl) {
      browser.tabs.create({ url: twentyUrl });
    }
  }

  function openRecord(record: { twentyId: string; type: string }) {
    if (twentyUrl) {
      // URL uses singular: /object/person/ and /object/company/
      browser.tabs.create({
        url: `${twentyUrl}/object/${record.type}/${record.twentyId}`,
      });
    }
  }

  function formatDate(timestamp: number): string {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();

    if (diff < 60000) return "Just now";
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`;
    return date.toLocaleDateString();
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "Enter") {
      saveSettings();
    }
  }

  return (
    <div className="w-full max-w-[500px] min-h-screen font-sans bg-card/10">
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-[60px] px-5 gap-3 ">
          <div className="w-6 h-6 border-2 rounded-full animate-spin"></div>
          <span>Loading...</span>
        </div>
      ) : (
        <main className="mx-4 pb-5 mt-4">
          {isConfigured && hasToken && (
            <section className="mb-5">
              {currentTabUrl && getLinkedInPageType(currentTabUrl) ? (
                <div className="bg-card rounded-lg p-4 border ">
                  {captureState.data && (
                    <div className="mb-3 flex flex-col gap-2">
                      <div className="flex items-center gap-2">
                        <Avatar>
                          <AvatarFallback>
                            <User className="size-4" />
                          </AvatarFallback>
                        </Avatar>
                        <h1 className="font-semibold text-xl">
                          {captureState.data.type === "person"
                            ? `${captureState.data.firstName} ${captureState.data.lastName}`
                            : captureState.data.name}
                        </h1>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">
                          {captureState.data.type === "person"
                            ? (captureState.data
                                .headline as LinkedInProfileData["headline"])
                            : captureState.data.description}
                        </p>
                        <p className="text-sm text-muted-foreground">
                          {captureState.data.type === "person"
                            ? captureState.data.currentCompany
                            : captureState.data.industry}
                        </p>
                      </div>
                    </div>
                  )}
                  <Button
                    variant="default"
                    className="w-full"
                    onClick={() => {
                      if (captureState.status === "ready") {
                        handleCapture();
                      } else if (
                        captureState.status === "exists" ||
                        captureState.status === "saved"
                      ) {
                        handleOpenInTwenty();
                      } else if (
                        captureState.status === "error" ||
                        captureState.status === "idle"
                      ) {
                        checkCurrentTab();
                      }
                    }}
                    disabled={
                      captureState.status === "loading" ||
                      captureState.status === "saving"
                    }
                  >
                    {(captureState.status === "loading" ||
                      captureState.status === "saving") && (
                      <div className="w-4 h-4 border-2 border-border border-t-transparent rounded-full animate-spin"></div>
                    )}
                    <Sparkles />
                    <span>{getCaptureButtonText()}</span>
                  </Button>
                  {captureState.status === "exists" && (
                    <Button
                      className="mt-2 w-full"
                      variant="secondary"
                      onClick={handleUpdate}
                    >
                      <RefreshCw className="size-4" />
                      Refresh data from LinkedIn
                    </Button>
                  )}
                </div>
              ) : (
                <div className="bg-sidebar rounded-lg p-4 border ">
                  <div className="flex items-center gap-2 mb-2">
                    <h3 className="text-sm font-semibold ">
                      Not on a LinkedIn Page
                    </h3>
                  </div>
                  <p className="text-xs  mb-3">
                    Navigate to a LinkedIn profile or company page to capture
                    it.
                  </p>
                  <Button
                    onClick={checkCurrentTab}
                    className="w-full"
                    variant="outline"
                    size="sm"
                    title="Refresh"
                  >
                    Refresh Current Tab
                  </Button>
                </div>
              )}
            </section>
          )}

          {isConfigured && !hasToken && (
            <section className="mb-4">
              <p className="text-sm text-muted-foreground mb-3">
                Please log in to your Twenty instance to use the extension.
              </p>
              <Button onClick={openTwenty} size="sm" className="w-full">
                Open Twenty →
              </Button>
            </section>
          )}

          {recentCaptures.length > 0 && (
            <section className="mb-5">
              <Label className="text-sm font-medium">Recently Added</Label>
              <ul className="list-none p-0 mt-2">
                {recentCaptures.map((capture) => (
                  <li
                    key={capture.twentyId}
                    className="flex items-center gap-3 px-3 py-2.5 bg-sidebar rounded-lg mb-2 cursor-pointer transition-colors hover:bg-sidebar/80"
                    onClick={() => openRecord(capture)}
                  >
                    <div className="flex items-center justify-center w-8 h-8 bg-red-200 rounded-full ">
                      {capture.type === "person" ? (
                        <Avatar>
                          <AvatarFallback>
                            <User className="size-4" />
                          </AvatarFallback>
                        </Avatar>
                      ) : (
                        <Avatar>
                          <AvatarFallback>
                            <Building2 className="size-4" />
                          </AvatarFallback>
                        </Avatar>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <span className="block text-sm font-medium whitespace-nowrap overflow-hidden text-ellipsis">
                        {capture.name}
                      </span>
                      <span className="text-xs ">
                        {formatDate(capture.capturedAt)}
                      </span>
                    </div>
                    <Link className="size-3" />
                  </li>
                ))}
              </ul>
            </section>
          )}

          <section className="mb-5">
            <div className="grid w-full items-center gap-3">
              <Label htmlFor="twentyUrl">
                <a
                  className="flex items-center gap-2"
                  href={twentyUrl}
                  target="_blank"
                >
                  Twenty URL
                  <ExternalLink className="size-4" />
                </a>
              </Label>
              <InputGroup>
                <InputGroupInput
                  placeholder="https://your-twenty.com"
                  value={twentyUrl}
                  onChange={(e) => setTwentyUrl(e.target.value)}
                  onKeyDown={handleKeyDown}
                />

                <InputGroupAddon align="inline-end">
                  <Badge variant="secondary" className="">
                    {statusText}
                  </Badge>
                </InputGroupAddon>
              </InputGroup>

              <p className="text-xs text-muted-foreground ">
                Your self-hosted Twenty instance URL
              </p>
            </div>

            <div className="flex gap-2 pt-4">
              <Button
                className="flex-1"
                variant="ghost"
                disabled={isSaving}
                onClick={saveSettings}
              >
                {isSaving ? "Saving..." : "Save"}
              </Button>
              <Button
                className="flex-1"
                variant="outline"
                disabled={isTesting || !isConfigured}
                onClick={testConnection}
              >
                {isTesting ? "Testing..." : "Test Connection"}
              </Button>
            </div>

            {error && (
              <div className="mt-3 px-3 py-2.5 rounded-lg text-[13px] bg-sidebar text-red-600">
                {error}
              </div>
            )}
            {success && (
              <div className="mt-3 px-3 py-2.5 rounded-lg text-[13px] bg-sidebar text-green-600">
                {success}
              </div>
            )}
          </section>
        </main>
      )}
    </div>
  );
}

// entrypoints/popup/App.vue
<script lang="ts" setup>
import { ref, onMounted, computed } from 'vue';
import type { ExtensionResponse } from '../../types';

// State
const twentyUrl = ref('');
const hasToken = ref(false);
const isConnected = ref(false);
const isLoading = ref(true);
const isSaving = ref(false);
const isTesting = ref(false);
const error = ref<string | null>(null);
const success = ref<string | null>(null);
const recentCaptures = ref<Array<{
  linkedinUrl: string;
  name: string;
  type: 'person' | 'company';
  capturedAt: number;
  twentyId: string;
}>>([]);

// Computed
const isConfigured = computed(() => !!twentyUrl.value);
const connectionStatus = computed(() => {
  if (!isConfigured.value) return 'not-configured';
  if (!hasToken.value) return 'no-session';
  if (isConnected.value) return 'connected';
  return 'disconnected';
});

const statusText = computed(() => {
  switch (connectionStatus.value) {
    case 'not-configured': return 'Not configured';
    case 'no-session': return 'Not logged in';
    case 'connected': return 'Connected';
    case 'disconnected': return 'Connection failed';
    default: return 'Unknown';
  }
});

const statusClass = computed(() => {
  switch (connectionStatus.value) {
    case 'connected': return 'status--connected';
    case 'no-session': return 'status--warning';
    default: return 'status--error';
  }
});

// Load settings on mount
onMounted(async () => {
  await loadSettings();
  await loadRecentCaptures();
});

async function loadSettings() {
  isLoading.value = true;
  try {
    const response = await browser.runtime.sendMessage({
      type: 'GET_SETTINGS',
    }) as ExtensionResponse<{ twentyUrl: string; hasToken: boolean }>;
    
    if (response.success && response.data) {
      twentyUrl.value = response.data.twentyUrl || '';
      hasToken.value = response.data.hasToken || false;
      
      if (hasToken.value) {
        await testConnection();
      }
    }
  } catch (err) {
    console.error('Error loading settings:', err);
    error.value = 'Failed to load settings';
  } finally {
    isLoading.value = false;
  }
}

async function loadRecentCaptures() {
  try {
    const response = await browser.runtime.sendMessage({
      type: 'GET_RECENT_CAPTURES',
    }) as ExtensionResponse<typeof recentCaptures.value>;
    
    if (response.success && response.data) {
      recentCaptures.value = response.data;
    }
  } catch (err) {
    console.error('Error loading recent captures:', err);
  }
}

async function saveSettings() {
  if (!twentyUrl.value) {
    error.value = 'Please enter your Twenty URL';
    return;
  }
  
  // Normalize URL
  let url = twentyUrl.value.trim();
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    url = 'https://' + url;
  }
  url = url.replace(/\/$/, ''); // Remove trailing slash
  twentyUrl.value = url;
  
  isSaving.value = true;
  error.value = null;
  success.value = null;
  
  try {
    const response = await browser.runtime.sendMessage({
      type: 'SAVE_SETTINGS',
      payload: { twentyUrl: url },
    }) as ExtensionResponse;
    
    if (response.success) {
      success.value = 'Settings saved!';
      // Reload to check token
      await loadSettings();
    } else {
      error.value = response.error || 'Failed to save settings';
    }
  } catch (err) {
    console.error('Error saving settings:', err);
    error.value = 'Failed to save settings';
  } finally {
    isSaving.value = false;
    setTimeout(() => { success.value = null; }, 3000);
  }
}

async function testConnection() {
  isTesting.value = true;
  error.value = null;
  
  try {
    const response = await browser.runtime.sendMessage({
      type: 'TEST_CONNECTION',
    }) as ExtensionResponse<{ connected: boolean }>;
    
    isConnected.value = response.success && response.data?.connected === true;
    
    if (!isConnected.value) {
      error.value = 'Connection test failed. Check your URL and login.';
    }
  } catch (err) {
    console.error('Error testing connection:', err);
    isConnected.value = false;
    error.value = 'Connection test failed';
  } finally {
    isTesting.value = false;
  }
}

function openTwenty() {
  if (twentyUrl.value) {
    browser.tabs.create({ url: twentyUrl.value });
  }
}

function openRecord(record: { twentyId: string; type: string }) {
  if (twentyUrl.value) {
    // URL uses singular: /object/person/ and /object/company/
    browser.tabs.create({ 
      url: `${twentyUrl.value}/object/${record.type}/${record.twentyId}` 
    });
  }
}

function formatDate(timestamp: number): string {
  const date = new Date(timestamp);
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  
  if (diff < 60000) return 'Just now';
  if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`;
  return date.toLocaleDateString();
}
</script>

<template>
  <div class="popup">
    <!-- Header -->
    <header class="header">
      <div class="header__logo">
        <svg width="24" height="24" viewBox="0 0 40 40" fill="none">
          <rect width="40" height="40" rx="8" fill="#6366f1"/>
          <path d="M12 14h16v3H12zM12 20h12v3H12zM12 26h8v3H12z" fill="white"/>
        </svg>
        <span class="header__title">Twenty CRM</span>
      </div>
      <div :class="['status-badge', statusClass]">
        <span class="status-dot"></span>
        {{ statusText }}
      </div>
    </header>

    <!-- Loading State -->
    <div v-if="isLoading" class="loading">
      <div class="spinner"></div>
      <span>Loading...</span>
    </div>

    <!-- Main Content -->
    <main v-else class="content">
      <!-- Settings Section -->
      <section class="section">
        <h2 class="section__title">Settings</h2>
        
        <div class="form-group">
          <label class="label" for="twentyUrl">Twenty URL</label>
          <input
            id="twentyUrl"
            v-model="twentyUrl"
            type="url"
            class="input"
            placeholder="https://your-twenty.com"
            @keyup.enter="saveSettings"
          />
          <p class="hint">Your self-hosted Twenty instance URL</p>
        </div>

        <div class="button-group">
          <button 
            class="btn btn--primary" 
            :disabled="isSaving"
            @click="saveSettings"
          >
            {{ isSaving ? 'Saving...' : 'Save' }}
          </button>
          <button 
            class="btn btn--secondary" 
            :disabled="isTesting || !isConfigured"
            @click="testConnection"
          >
            {{ isTesting ? 'Testing...' : 'Test Connection' }}
          </button>
        </div>

        <!-- Messages -->
        <div v-if="error" class="message message--error">
          {{ error }}
        </div>
        <div v-if="success" class="message message--success">
          {{ success }}
        </div>
      </section>

      <!-- Login Prompt -->
      <section v-if="isConfigured && !hasToken" class="section section--warning">
        <p class="warning-text">
          Please log in to your Twenty instance to use the extension.
        </p>
        <button class="btn btn--primary" @click="openTwenty">
          Open Twenty →
        </button>
      </section>

      <!-- Recent Captures -->
      <section v-if="recentCaptures.length > 0" class="section">
        <h2 class="section__title">Recent Captures</h2>
        <ul class="captures-list">
          <li 
            v-for="capture in recentCaptures" 
            :key="capture.twentyId"
            class="capture-item"
            @click="openRecord(capture)"
          >
            <div class="capture-item__icon">
              <svg v-if="capture.type === 'person'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
                <circle cx="12" cy="7" r="4"/>
              </svg>
              <svg v-else width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M3 21h18M9 8h1M9 12h1M9 16h1M14 8h1M14 12h1M14 16h1M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16"/>
              </svg>
            </div>
            <div class="capture-item__info">
              <span class="capture-item__name">{{ capture.name }}</span>
              <span class="capture-item__time">{{ formatDate(capture.capturedAt) }}</span>
            </div>
            <svg class="capture-item__arrow" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M9 18l6-6-6-6"/>
            </svg>
          </li>
        </ul>
      </section>

      <!-- Instructions -->
      <section class="section section--muted">
        <h2 class="section__title">How to use</h2>
        <ol class="instructions">
          <li>Enter your Twenty CRM URL above</li>
          <li>Log in to Twenty in your browser</li>
          <li>Visit any LinkedIn profile or company page</li>
          <li>Click the floating button to capture</li>
        </ol>
      </section>
    </main>
  </div>
</template>

<style scoped>
.popup {
  width: 360px;
  min-height: 400px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #fafafa;
  color: #1f2937;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px;
  background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
  color: white;
}

.header__logo {
  display: flex;
  align-items: center;
  gap: 10px;
}

.header__title {
  font-size: 16px;
  font-weight: 600;
}

.status-badge {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: 500;
  background: rgba(255, 255, 255, 0.2);
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: currentColor;
}

.status--connected {
  color: #34d399;
}

.status--warning {
  color: #fbbf24;
}

.status--error {
  color: #f87171;
}

.loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
  gap: 12px;
  color: #6b7280;
}

.spinner {
  width: 24px;
  height: 24px;
  border: 2px solid #e5e7eb;
  border-top-color: #6366f1;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.content {
  padding: 16px 20px 20px;
}

.section {
  margin-bottom: 20px;
}

.section--warning {
  background: #fef3c7;
  padding: 16px;
  border-radius: 8px;
  margin: 0 -20px 20px;
  padding-left: 20px;
  padding-right: 20px;
}

.section--muted {
  opacity: 0.8;
}

.section__title {
  font-size: 13px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #6b7280;
  margin-bottom: 12px;
}

.form-group {
  margin-bottom: 16px;
}

.label {
  display: block;
  font-size: 14px;
  font-weight: 500;
  margin-bottom: 6px;
  color: #374151;
}

.input {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  font-size: 14px;
  transition: border-color 0.2s, box-shadow 0.2s;
  box-sizing: border-box;
}

.input:focus {
  outline: none;
  border-color: #6366f1;
  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
}

.hint {
  font-size: 12px;
  color: #9ca3af;
  margin-top: 4px;
}

.button-group {
  display: flex;
  gap: 8px;
}

.btn {
  flex: 1;
  padding: 10px 16px;
  border: none;
  border-radius: 8px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn--primary {
  background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
  color: white;
}

.btn--primary:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
}

.btn--secondary {
  background: #e5e7eb;
  color: #374151;
}

.btn--secondary:hover:not(:disabled) {
  background: #d1d5db;
}

.message {
  margin-top: 12px;
  padding: 10px 12px;
  border-radius: 8px;
  font-size: 13px;
}

.message--error {
  background: #fef2f2;
  color: #dc2626;
}

.message--success {
  background: #f0fdf4;
  color: #16a34a;
}

.warning-text {
  font-size: 14px;
  color: #92400e;
  margin-bottom: 12px;
}

.captures-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.capture-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  background: white;
  border-radius: 8px;
  margin-bottom: 8px;
  cursor: pointer;
  transition: background 0.2s;
}

.capture-item:hover {
  background: #f3f4f6;
}

.capture-item__icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  background: #e5e7eb;
  border-radius: 50%;
  color: #6b7280;
}

.capture-item__info {
  flex: 1;
  min-width: 0;
}

.capture-item__name {
  display: block;
  font-size: 14px;
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.capture-item__time {
  font-size: 12px;
  color: #9ca3af;
}

.capture-item__arrow {
  color: #9ca3af;
}

.instructions {
  font-size: 13px;
  padding-left: 20px;
  margin: 0;
  color: #6b7280;
}

.instructions li {
  margin-bottom: 6px;
}

.instructions li:last-child {
  margin-bottom: 0;
}
</style>
